import type { EmployeeProfile } from './employee-profile-types'

export const EMPLOYEES_FULL: EmployeeProfile[] = [
  {
    id: 'e1',
    name: 'محمود شعراوي',
    employeeNumber: 'EMP001',
    position: 'مشرف إنتاج',
    hireDate: '2023-01-15',
    salary: 8000,
    insurance: 1200,
    status: 'active',
    email: 'mahmoud@bigboos.com',
    phone: '01012345678',
    nationalId: '29501011234567',
    address: 'القاهرة - مدينة نصر',
    department: 'الإنتاج',
    role: 'manager',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: true },
      machines: { view: true, create: true, edit: true, delete: false },
      attendance: { view: true, create: true, edit: true, delete: false },
      accounting: { view: true, create: false, edit: false, delete: false },
      users: { view: true, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'الصباحي',
      checkIn: '08:00',
      checkOut: '16:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    commission: {
      enabled: true,
      type: 'percentage',
      value: 5,
      notes: 'عمولة على المبيعات الشهرية',
      history: [
        { date: '2024-10-01', amount: 400, description: 'عمولة شهر أكتوبر' },
        { date: '2024-09-01', amount: 380, description: 'عمولة شهر سبتمبر' },
      ],
    },
    documents: {
      idCard: {
        url: '/documents/mahmoud-id.pdf',
        uploadedAt: '2023-01-15',
      },
      other: [],
    },
  },
  {
    id: 'e2',
    name: 'شيماء عمر',
    employeeNumber: 'EMP002',
    position: 'موظفة تصميم',
    hireDate: '2023-03-20',
    salary: 6000,
    insurance: 900,
    status: 'active',
    email: 'shimaa@bigboos.com',
    phone: '01023456789',
    nationalId: '29601021234568',
    address: 'القاهرة - المعادي',
    department: 'التصميم',
    role: 'employee',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: false },
      machines: { view: true, create: false, edit: false, delete: false },
      attendance: { view: true, create: true, edit: false, delete: false },
      accounting: { view: false, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'الصباحي',
      checkIn: '08:00',
      checkOut: '16:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    documents: {
      other: [],
    },
  },
  {
    id: 'e3',
    name: 'مصطفي عادل',
    employeeNumber: 'EMP003',
    position: 'موظف طباعة',
    hireDate: '2023-05-10',
    salary: 5500,
    insurance: 825,
    status: 'active',
    email: 'mostafa.adel@bigboos.com',
    phone: '01034567890',
    nationalId: '29701031234569',
    address: 'الجيزة - الهرم',
    department: 'الطباعة',
    role: 'employee',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: false },
      machines: { view: true, create: false, edit: true, delete: false },
      attendance: { view: true, create: true, edit: false, delete: false },
      accounting: { view: false, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'الصباحي',
      checkIn: '08:00',
      checkOut: '16:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    documents: {
      other: [],
    },
  },
  {
    id: 'e4',
    name: 'ايهاب سعيد',
    employeeNumber: 'EMP004',
    position: 'موظف قص ليزر',
    hireDate: '2023-07-01',
    salary: 5800,
    insurance: 870,
    status: 'active',
    email: 'ehab@bigboos.com',
    phone: '01045678901',
    nationalId: '29801041234570',
    address: 'القاهرة - شبرا',
    department: 'القص والتشطيب',
    role: 'employee',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: false },
      machines: { view: true, create: false, edit: true, delete: false },
      attendance: { view: true, create: true, edit: false, delete: false },
      accounting: { view: false, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'المسائي',
      checkIn: '14:00',
      checkOut: '22:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    documents: {
      other: [],
    },
  },
  {
    id: 'e5',
    name: 'مصطفي ابراهيم',
    employeeNumber: 'EMP005',
    position: 'موظف حفر ليزر',
    hireDate: '2023-08-15',
    salary: 6200,
    insurance: 930,
    status: 'active',
    email: 'mostafa.ibrahim@bigboos.com',
    phone: '01056789012',
    nationalId: '29901051234571',
    address: 'القاهرة - مصر الجديدة',
    department: 'الحفر والنقش',
    role: 'employee',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: false },
      machines: { view: true, create: false, edit: true, delete: false },
      attendance: { view: true, create: true, edit: false, delete: false },
      accounting: { view: false, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'المسائي',
      checkIn: '14:00',
      checkOut: '22:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    documents: {
      other: [],
    },
  },
  {
    id: 'e6',
    name: 'انس عماد',
    employeeNumber: 'EMP006',
    position: 'موظف يوفي',
    hireDate: '2023-09-20',
    salary: 5200,
    insurance: 780,
    status: 'active',
    email: 'anas@bigboos.com',
    phone: '01067890123',
    nationalId: '30001061234572',
    address: 'الجيزة - المهندسين',
    department: 'الطباعة',
    role: 'employee',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: false },
      machines: { view: true, create: false, edit: true, delete: false },
      attendance: { view: true, create: true, edit: false, delete: false },
      accounting: { view: false, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'الصباحي',
      checkIn: '08:00',
      checkOut: '16:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    documents: {
      other: [],
    },
  },
  {
    id: 'e7',
    name: 'صابر سيد',
    employeeNumber: 'EMP007',
    position: 'موظف تشطيب',
    hireDate: '2023-10-10',
    salary: 5000,
    insurance: 750,
    status: 'active',
    email: 'saber@bigboos.com',
    phone: '01078901234',
    nationalId: '30101071234573',
    address: 'القاهرة - الزيتون',
    department: 'التشطيب',
    role: 'employee',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: false },
      machines: { view: true, create: false, edit: false, delete: false },
      attendance: { view: true, create: true, edit: false, delete: false },
      accounting: { view: false, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'المسائي',
      checkIn: '14:00',
      checkOut: '22:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    documents: {
      other: [],
    },
  },
  {
    id: 'e8',
    name: 'ثابت احمد',
    employeeNumber: 'EMP008',
    position: 'موظف تغليف',
    hireDate: '2023-11-05',
    salary: 4800,
    insurance: 720,
    status: 'active',
    email: 'thabet@bigboos.com',
    phone: '01089012345',
    nationalId: '30201081234574',
    address: 'القاهرة - المطرية',
    department: 'التشطيب',
    role: 'employee',
    permissions: {
      tasks: { view: true, create: true, edit: true, delete: false },
      machines: { view: true, create: false, edit: false, delete: false },
      attendance: { view: true, create: true, edit: false, delete: false },
      accounting: { view: false, create: false, edit: false, delete: false },
      users: { view: false, create: false, edit: false, delete: false },
    },
    workSchedule: {
      shift: 'الصباحي',
      checkIn: '08:00',
      checkOut: '16:00',
      workDays: ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
    },
    documents: {
      other: [],
    },
  },
]

export function getEmployeeProfileById(id: string): EmployeeProfile | undefined {
  return EMPLOYEES_FULL.find((emp) => emp.id === id)
}
