import type { Machine } from "./machines-types"

export const MACHINES: Machine[] = [
  {
    id: "m1",
    name: "ماكينة حفر ليزر فايبر 1",
    model: "Raycus 30W",
    serialNumber: "RAY-30-2023-001",
    purchaseDate: "2023-01-15",
    purchasePrice: 150000,
    currentValue: 135000,
    status: "working",
    category: "fiber-laser",
    maintenanceEngineer: "م. خالد محمود",
    engineerPhone: "01012345678",
    maintenanceSchedule: "quarterly",
    nextMaintenanceDate: "2024-12-15",
    lastMaintenanceDate: "2024-09-15",
    visitCost: 1500,
    spareParts: [
      { name: "عدسة التركيز", cost: 2500, replacementPeriod: 6 },
      { name: "مرآة الليزر", cost: 1800, replacementPeriod: 12 },
      { name: "فلتر الهواء", cost: 300, replacementPeriod: 3 },
    ],
    operatingCosts: {
      electricityCostPerHour: 15,
      maintenanceCostPerMonth: 800,
    },
    services: [
      {
        id: "s1",
        name: "حفر ليزر فايبر",
        unit: "سم²",
        costPerUnit: 1.5,
        pricePerUnit: {
          individual: 3,
          company: 2.5,
          advertisingOffice: 2,
        },
        sizeBasedPricing: {
          minSize: 1,
          maxSize: 100,
          baseCost: 2,
          pricePerCmSquared: 1,
        },
      },
    ],
    totalRevenue: 45000,
    totalOperatingHours: 850,
    totalJobs: 124,
  },
  {
    id: "m2",
    name: "ماكينة قص ليزر CO2",
    model: "CO2-150W",
    serialNumber: "CO2-150-2022-002",
    purchaseDate: "2022-06-20",
    purchasePrice: 200000,
    currentValue: 170000,
    status: "working",
    category: "co2-laser",
    maintenanceEngineer: "م. أحمد سعيد",
    engineerPhone: "01098765432",
    maintenanceSchedule: "quarterly",
    nextMaintenanceDate: "2024-11-30",
    lastMaintenanceDate: "2024-08-30",
    visitCost: 2000,
    spareParts: [
      { name: "أنبوب الليزر", cost: 15000, replacementPeriod: 24 },
      { name: "عدسة القطع", cost: 3000, replacementPeriod: 6 },
      { name: "حزام النقل", cost: 800, replacementPeriod: 12 },
    ],
    operatingCosts: {
      electricityCostPerHour: 25,
      maintenanceCostPerMonth: 1200,
    },
    services: [
      {
        id: "s2",
        name: "قص ليزر CO2",
        unit: "دقيقة",
        costPerUnit: 3,
        pricePerUnit: {
          individual: 5,
          company: 4.5,
          advertisingOffice: 4,
        },
      },
    ],
    totalRevenue: 68000,
    totalOperatingHours: 1200,
    totalJobs: 230,
  },
  {
    id: "m3",
    name: "طابعة يوفي",
    model: "UV-6090",
    serialNumber: "UV-6090-2023-003",
    purchaseDate: "2023-03-10",
    purchasePrice: 180000,
    currentValue: 165000,
    status: "working",
    category: "uv-printer",
    maintenanceEngineer: "م. محمد فتحي",
    engineerPhone: "01123456789",
    maintenanceSchedule: "quarterly",
    nextMaintenanceDate: "2024-12-10",
    lastMaintenanceDate: "2024-09-10",
    visitCost: 1800,
    spareParts: [
      { name: "رأس الطباعة", cost: 8000, replacementPeriod: 18 },
      { name: "لمبة UV", cost: 4000, replacementPeriod: 6 },
      { name: "فلتر الحبر", cost: 500, replacementPeriod: 3 },
    ],
    operatingCosts: {
      electricityCostPerHour: 20,
      maintenanceCostPerMonth: 1000,
    },
    services: [
      {
        id: "s3",
        name: "طباعة يوفي",
        unit: "سم²",
        costPerUnit: 2,
        pricePerUnit: {
          individual: 4,
          company: 3.5,
          advertisingOffice: 3,
        },
      },
    ],
    totalRevenue: 52000,
    totalOperatingHours: 980,
    totalJobs: 156,
  },
]
