// Products data - separated for better performance
export interface Product {
  id: number
  name: string
  description: string
  category: string
  price: number
  originalPrice: number | null
  image: string
  rating: number
  reviews: number
  badge: string | null
  badgeColor: string | null
  sizes: string[]
  colors: string[]
  printTypes: string[]
  features: string[]
  deliveryTime: string
  minOrder: number
}

export const allProducts: Product[] = [
  {
    id: 1,
    name: "كروت شخصية فاخرة",
    description: "كروت شخصية احترافية مطبوعة على ورق فاخر 350 جرام مع تشطيب لامع أو مط.",
    category: "print",
    price: 150,
    originalPrice: 200,
    image: "/products/business-cards.jpg",
    rating: 4.9,
    reviews: 234,
    badge: "الأكثر مبيعاً",
    badgeColor: "bg-red-500",
    sizes: ["100 كارت", "250 كارت", "500 كارت", "1000 كارت"],
    colors: ["أبيض", "كريمي", "رمادي فاتح"],
    printTypes: ["طباعة وجه واحد", "طباعة وجهين"],
    features: ["ورق فاخر 350 جرام", "ألوان CMYK كاملة", "تشطيب مط أو لامع"],
    deliveryTime: "3-5 أيام عمل",
    minOrder: 100,
  },
  {
    id: 2,
    name: "تيشيرت قطن 100%",
    description: "تيشيرت قطن عالي الجودة مناسب للطباعة بجميع التقنيات.",
    category: "apparel",
    price: 85,
    originalPrice: null,
    image: "/products/tshirt.jpg",
    rating: 4.8,
    reviews: 189,
    badge: null,
    badgeColor: null,
    sizes: ["S", "M", "L", "XL", "XXL", "XXXL"],
    colors: ["أبيض", "أسود", "كحلي", "رمادي", "أحمر", "أزرق"],
    printTypes: ["طباعة حرارية", "طباعة سلك سكرين", "تطريز"],
    features: ["قطن 100%", "مريح للبشرة", "ثبات الألوان"],
    deliveryTime: "5-7 أيام عمل",
    minOrder: 10,
  },
  {
    id: 3,
    name: "بروشور مطوي A4",
    description: "بروشور ثلاثي الطي مطبوع على ورق كوشيه لامع أو مط.",
    category: "print",
    price: 250,
    originalPrice: 300,
    image: "/products/brochure.jpg",
    rating: 4.7,
    reviews: 156,
    badge: "خصم 17%",
    badgeColor: "bg-green-500",
    sizes: ["100 بروشور", "250 بروشور", "500 بروشور", "1000 بروشور"],
    colors: ["طباعة ألوان كاملة"],
    printTypes: ["طباعة وجه واحد", "طباعة وجهين"],
    features: ["ورق كوشيه 150 جرام", "طي ثلاثي احترافي", "ألوان حية"],
    deliveryTime: "4-6 أيام عمل",
    minOrder: 100,
  },
  {
    id: 4,
    name: "أكواب سيراميك مطبوعة",
    description: "أكواب سيراميك عالية الجودة مع طباعة حرارية ثابتة.",
    category: "promo",
    price: 45,
    originalPrice: null,
    image: "/products/mug.jpg",
    rating: 4.9,
    reviews: 312,
    badge: "جديد",
    badgeColor: "bg-blue-500",
    sizes: ["11 أونصة", "15 أونصة"],
    colors: ["أبيض", "أسود من الداخل", "ملون كامل"],
    printTypes: ["طباعة حرارية", "طباعة 360 درجة"],
    features: ["سيراميك عالي الجودة", "طباعة ثابتة", "آمن للميكروويف"],
    deliveryTime: "5-7 أيام عمل",
    minOrder: 12,
  },
  {
    id: 5,
    name: "رول أب ستاند 85x200",
    description: "ستاند رول أب احترافي مع طباعة عالية الدقة.",
    category: "signage",
    price: 350,
    originalPrice: 450,
    image: "/products/rollup.jpg",
    rating: 4.6,
    reviews: 98,
    badge: "خصم 22%",
    badgeColor: "bg-green-500",
    sizes: ["85x200 سم", "100x200 سم", "120x200 سم"],
    colors: ["طباعة ألوان كاملة"],
    printTypes: ["طباعة إيكوسولفنت", "طباعة UV"],
    features: ["ستاند ألومنيوم متين", "سهل التركيب", "حقيبة حمل"],
    deliveryTime: "3-5 أيام عمل",
    minOrder: 1,
  },
  {
    id: 6,
    name: "فلاير دعائي A5",
    description: "فلايرات دعائية مطبوعة بجودة عالية على ورق كوشيه.",
    category: "print",
    price: 180,
    originalPrice: 220,
    image: "/products/flyer.jpg",
    rating: 4.8,
    reviews: 267,
    badge: "خصم 18%",
    badgeColor: "bg-green-500",
    sizes: ["500 فلاير", "1000 فلاير", "2000 فلاير", "5000 فلاير"],
    colors: ["طباعة ألوان كاملة"],
    printTypes: ["طباعة وجه واحد", "طباعة وجهين"],
    features: ["ورق كوشيه 135 جرام", "ألوان CMYK", "قص دقيق"],
    deliveryTime: "3-5 أيام عمل",
    minOrder: 500,
  },
  {
    id: 7,
    name: "بولو شيرت مطرز",
    description: "بولو شيرت قطن بيكيه عالي الجودة مع تطريز احترافي.",
    category: "apparel",
    price: 120,
    originalPrice: 150,
    image: "/products/polo.jpg",
    rating: 4.7,
    reviews: 143,
    badge: "خصم 20%",
    badgeColor: "bg-green-500",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["أبيض", "أسود", "كحلي", "بترولي", "عنابي"],
    printTypes: ["تطريز", "طباعة حرارية"],
    features: ["قطن بيكيه 220 جرام", "ياقة مزدوجة", "أزرار فاخرة"],
    deliveryTime: "7-10 أيام عمل",
    minOrder: 10,
  },
  {
    id: 8,
    name: "ميداليات معدنية",
    description: "ميداليات معدنية مخصصة بتصميمك للهدايا والجوائز.",
    category: "promo",
    price: 25,
    originalPrice: null,
    image: "/products/keychain.jpg",
    rating: 4.5,
    reviews: 89,
    badge: null,
    badgeColor: null,
    sizes: ["4 سم", "5 سم", "6 سم"],
    colors: ["فضي", "ذهبي", "برونزي", "ملون"],
    printTypes: ["حفر ليزر", "طباعة UV", "مينا ملونة"],
    features: ["معدن عالي الجودة", "تشطيب فاخر", "حلقة متينة"],
    deliveryTime: "7-10 أيام عمل",
    minOrder: 50,
  },
]
